/* ─── JS PROGRESSIVE ENHANCEMENT ────────────────────────── */
document.documentElement.classList.add('js');

/* ─── NAV SCROLL BORDER ──────────────────────────────────── */
(function () {
  const nav = document.getElementById('nav');
  if (!nav) return;
  const onScroll = () => {
    nav.classList.toggle('scrolled', window.scrollY > 8);
  };
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll(); // set initial state in case page loads already scrolled
})();

/* ─── SCROLL FADE-IN ─────────────────────────────────────── */
(function () {
  const els = document.querySelectorAll('.fade-in');
  if (!('IntersectionObserver' in window)) {
    els.forEach(el => el.classList.add('visible'));
    return;
  }
  const io = new IntersectionObserver(
    (entries) => {
      entries.forEach(e => {
        if (e.isIntersecting) {
          e.target.classList.add('visible');
          io.unobserve(e.target);
        }
      });
    },
    { threshold: 0.12 }
  );
  els.forEach(el => io.observe(el));
})();

/* ─── COPY BUTTON ────────────────────────────────────────── */
(function () {
  const btn = document.getElementById('copyBtn');
  const label = document.getElementById('copyLabel');
  if (!btn) return;

  btn.addEventListener('click', () => {
    navigator.clipboard.writeText('brew install rinse').then(() => {
      label.textContent = 'Copied ✓';
      btn.classList.add('copied');
      setTimeout(() => {
        label.textContent = 'Copy';
        btn.classList.remove('copied');
      }, 2000);
    }).catch(() => {
      label.textContent = 'Failed';
      setTimeout(() => { label.textContent = 'Copy'; }, 2000);
    });
  });
})();

/* ─── TERMINAL TYPEWRITER ANIMATION ─────────────────────── */
(function () {
  const typedCmd  = document.getElementById('typedCmd');
  const cursor    = document.getElementById('cursor');
  const termOut   = document.getElementById('termOutput');
  if (!typedCmd || !termOut || !cursor) return;

  const CMD = 'rinse .';
  const OUTPUT_LINES = [
    { text: 'Scanning 47 files...', cls: 'tline-dim' },
    { text: '- // This code was generated by AI assistance.', cls: 'tline-red' },
    { text: '- // Note: the following was auto-completed.', cls: 'tline-red' },
    { text: '✓ Done. 12 AI comments cleaned.', cls: 'tline-green' },
  ];

  let phase = 'typing'; // typing | output | pausing
  let charIdx = 0;
  let lineIdx = 0;
  let timer;

  function clearOutput () {
    termOut.innerHTML = '';
  }

  function appendOutputLine (line) {
    const span = document.createElement('span');
    span.className = `tline ${line.cls}`;
    span.textContent = line.text;
    termOut.appendChild(span);
  }

  function reset () {
    typedCmd.textContent = '';
    clearOutput();
    charIdx = 0;
    lineIdx = 0;
    phase = 'typing';
    cursor.style.display = '';
    tick();
  }

  function tick () {
    clearTimeout(timer);

    if (phase === 'typing') {
      if (charIdx < CMD.length) {
        typedCmd.textContent = CMD.slice(0, charIdx + 1);
        charIdx++;
        timer = setTimeout(tick, 65 + Math.random() * 40);
      } else {
        // done typing — hide cursor, start output
        cursor.style.display = 'none';
        phase = 'output';
        timer = setTimeout(tick, 400);
      }
      return;
    }

    if (phase === 'output') {
      if (lineIdx < OUTPUT_LINES.length) {
        appendOutputLine(OUTPUT_LINES[lineIdx]);
        lineIdx++;
        timer = setTimeout(tick, lineIdx === 1 ? 600 : 300);
      } else {
        // all output printed — pause then restart
        phase = 'pausing';
        timer = setTimeout(reset, 3200);
      }
      return;
    }
  }

  // Start after a short delay so page load settles
  timer = setTimeout(tick, 800);
})();

/* ─── WAITLIST FORM ──────────────────────────────────────── */
(function () {
  const form = document.getElementById('waitlistForm');
  if (!form) return;
  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    const btn = form.querySelector('.waitlist-btn');
    const input = form.querySelector('.waitlist-input');
    if (!btn) return;
    const originalText = btn.textContent;
    try {
      const res = await fetch(form.action, {
        method: 'POST',
        body: new FormData(form),
        headers: { Accept: 'application/json' },
      });
      if (res.ok) {
        btn.textContent = 'You\'re on the list ✓';
        btn.disabled = true;
        if (input) input.disabled = true;
      } else {
        btn.textContent = 'Try again';
        setTimeout(() => { btn.textContent = originalText; }, 2500);
      }
    } catch {
      btn.textContent = 'Try again';
      setTimeout(() => { btn.textContent = originalText; }, 2500);
    }
  });
})();
