/* ── Copy Button ── */
(function () {
  const btn = document.getElementById('copyBtn');
  if (!btn) return;
  btn.addEventListener('click', function () {
    const cmd = btn.dataset.cmd;
    navigator.clipboard.writeText(cmd).then(function () {
      btn.classList.add('copied');
      btn.innerHTML = `
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <polyline points="20 6 9 17 4 12"/>
        </svg>
        Copied ✓`;
      setTimeout(function () {
        btn.classList.remove('copied');
        btn.innerHTML = `
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <rect x="9" y="9" width="13" height="13" rx="2"/>
            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
          </svg>
          Copy`;
      }, 2000);
    });
  });
})();

/* ── Nav scroll border ── */
(function () {
  var nav = document.getElementById('nav');
  if (!nav) return;
  window.addEventListener('scroll', function () {
    if (window.scrollY > 10) {
      nav.classList.add('scrolled');
    } else {
      nav.classList.remove('scrolled');
    }
  }, { passive: true });
})();

/* ── Scroll fade-in ── */
(function () {
  var elements = document.querySelectorAll('.fade-in');
  if (!elements.length) return;
  var observer = new IntersectionObserver(function (entries) {
    entries.forEach(function (entry, i) {
      if (entry.isIntersecting) {
        setTimeout(function () {
          entry.target.classList.add('visible');
        }, i * 80);
        observer.unobserve(entry.target);
      }
    });
  }, { threshold: 0.15 });
  elements.forEach(function (el) { observer.observe(el); });
})();

/* ── Terminal typewriter animation ── */
(function () {
  var lines = [
    { id: 'tl0', text: 'rinse .', type: 'cmd', cursorId: 'cursor0' },
    { id: 'tl1', text: 'Scanning 47 files...', type: 'plain' },
    { id: 'tl2', text: '- This code was generated by an AI assistant.', type: 'red' },
    { id: 'tl3', text: '+ [removed]', type: 'green' },
    { id: 'tl4', text: '✓ Done. 12 comments cleaned in 1.8s.', type: 'accent' },
  ];

  function typeText(el, text, cb) {
    var i = 0;
    var span = el.querySelector('.t-text');
    if (!span) { if (cb) cb(); return; }
    var cursor = el.querySelector('.cursor');
    function next() {
      if (i < text.length) {
        span.textContent += text[i++];
        setTimeout(next, 38 + Math.random() * 28);
      } else {
        if (cursor) cursor.style.display = 'none';
        if (cb) setTimeout(cb, 280);
      }
    }
    next();
  }

  function showLine(lineEl, cb) {
    lineEl.classList.remove('hidden');
    cb && setTimeout(cb, 60);
  }

  function runSequence() {
    // Reset
    lines.forEach(function (l) {
      var el = document.getElementById(l.id);
      if (!el) return;
      var span = el.querySelector('.t-text');
      var cursor = el.querySelector('.cursor');
      if (span) span.textContent = '';
      if (cursor) cursor.style.display = '';
      el.classList.add('hidden');
    });

    // Start typing cmd line first
    var cmdEl = document.getElementById('tl0');
    if (cmdEl) {
      cmdEl.classList.remove('hidden');
      typeText(cmdEl, lines[0].text, function () {
        var idx = 1;
        function nextLine() {
          if (idx >= lines.length) {
            // Pause then restart loop
            setTimeout(runSequence, 2800);
            return;
          }
          var l = lines[idx];
          var el = document.getElementById(l.id);
          if (!el) { idx++; nextLine(); return; }
          showLine(el, function () {
            var span = el.querySelector('.t-text');
            if (span) span.textContent = l.text;
            idx++;
            setTimeout(nextLine, 320);
          });
        }
        nextLine();
      });
    }
  }

  // Start after a short delay
  setTimeout(runSequence, 600);
})();

/* ── Waitlist form (progressive enhancement) ── */
(function () {
  var form = document.getElementById('waitlistForm');
  if (!form) return;
  form.addEventListener('submit', function (e) {
    e.preventDefault();
    var email = form.querySelector('input[type=email]').value;
    var btn = form.querySelector('.waitlist-btn');
    // Send via fetch to Formspree
    fetch(form.action, {
      method: 'POST',
      headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: email }),
    })
      .then(function (r) {
        if (r.ok) {
          form.innerHTML = '<p style="color:var(--accent);font-size:0.95rem;font-weight:500;">You\'re on the list. We\'ll be in touch.</p>';
        } else {
          if (btn) btn.textContent = 'Try again';
        }
      })
      .catch(function () {
        if (btn) btn.textContent = 'Try again';
      });
  });
})();
